This branch contains layout for desktop view and includes new image backgrounds
Solo7991/Module1Block1Portfolio pull request #2
Opened 2022-05-02 13:24 UTC by Solo7991

Changes are:
New image backgrounds and patterns for desktop users
Introduction of Formspree forms in the contact section
New Layout for desktop
Navigation links in the welcome section

2022-05-02 14:01 UTC, keroloussamy requested changes
Hi @Solo7991, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

## Required Changes ♻️
_Check the comments under the review._

![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-02 14:01 UTC, keroloussamy commented on index.html
> +                                    <input type="text" placeholder="jack32@gmail.com" id="email">
- [x] Kindly your email input should have `type="email"` not text kindly fix it.
- [x] Kindly your email input should have the `required` attribute.

2022-05-02 14:01 UTC, keroloussamy commented on index.html
> +                                </label>
- [x] Kindly your text area should have the `required` attribute.
- [x] Kindly your text area should have the `maxlength="500"` attribute.

2022-05-02 14:01 UTC, keroloussamy commented on index.html
> +                                    <input type="text" placeholder="Jack" id="name">
- [x] Kindly your name input should have the `required` attribute.
- [x] Kindly your name input should have the `maxlength="30"` attribute.

2022-05-02 14:01 UTC, keroloussamy commented on index.html
> +                                </label>
- [ ] Kindly add `name` attribute to all your form elements, to specify each one is the name and the email, and the message. and to make your form submission works.

- [ ] Kindly be sure that your form is working before you submit it again.

![image](https://user-images.githubusercontent.com/35535130/166246609-2a4f17ec-844f-4aae-a6ee-08b4a381af7f.png)

2022-05-02 15:34 UTC, topeogunleye approved these changes
### Hi @Solo7991, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
> 
> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-04 09:55 UTC, Solo7991 commented
This approval is for the desktop version of my portfolio. I created the form in the first week. Could I get approval for the "Add a contact form and finish the mobile version" project? How do I proceed?

2022-05-04 10:43 UTC, merged

2022-05-06 15:45 UTC, topeogunleye commented
> This approval is for the desktop version of my portfolio. I created the form in the first week. Could I get approval for the "Add a contact form and finish the mobile version" project? How do I proceed?

Kindly create a new branch, then make a new pull request after you are done with your feature